<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateContactsTable extends Migration
{
    public function up()
    {
        Schema::create('contacts', function (Blueprint $table) {
            $table->id();
            $table->string('form_type')->index();
            $table->string('reference_number')->index()->unique(); // Generated by system. This is identifier used to communicate with customer about their contact form. Reference number is emailed to them.
            $table->foreignIdFor(app('location'))->index();
            $table->foreignIdFor(app('email_address'))->index();
            $table->foreignIdFor(app('user'))->nullable()->index();
            $table->string('first_name')->nullable();
            $table->string('last_name')->nullable();
            $table->string('company_name')->nullable();
            $table->string('phone')->nullable(); // Will need to format before saving
            $table->text('message')->nullable();
            $table->json('fields')->nullable();

            $table->softDeletes(); // Soft delete if email bounces or if the contact submission is spam.
            $table->timestamps();
        });
    }
}
