<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateContactsTable extends Migration
{
    public function up()
    {
        Schema::create('contacts', function (Blueprint $table) {
            $table->id();
            $table->string('form_type')->index(); // String title of the form type so know which one was completed
            $table->string('reference_number')->index()->unique(); // Generated by system. This is identifier used to communicate with customer about their contact form. Reference number is emailed to them.
            $table->foreignIdFor(app('location'))->index();
            $table->string('email');
            $table->foreignIdFor(app('user'))->nullable()->index();
            $table->string('first_name')->nullable();
            $table->string('last_name')->nullable();
            $table->string('company_name')->nullable();
            $table->string('phone')->nullable(); // Will need to format before saving
            $table->text('message')->nullable();
            $table->json('additional_fields')->nullable();
            
            // Move application specific data to additonal_fields
            $table->smallInteger('participants')->nullable();
            $table->date('requested_date')->nullable();
            $table->time('requested_time')->nullable(); // Stored in location timezone
            
            // Move response fields to different table (contact followup or something like that)
            $table->dateTime('emailed_at')->nullable();
            $table->dateTime('closed_at')->nullable();
            
            $table->softDeletes(); // Soft delete if email bounces or if the contact submission is spam.
            $table->timestamps();
        });
    }
}
